version: '3'
services:
  marketing:
    build: .
    command: [ "sh", "startup.sh" ]
    ports:
      - 8000:8000
    volumes:
      - .:/work

networks:
  default:
    external:
      name: itprotv_bridge
