version: '3'
services:
  marketing:
    build: .
    command: "./startup.sh build $MARKETING_ENV"
    ports:
      - 8000:8000
    volumes:
      - .:/work

networks:
  default:
    external:
      name: itprotv_bridge
