version: '3'
services:
  marketing:
    build: .
    command: "./startup.sh develop"
    ports:
      - 8000:8000
    volumes:
      - .:/work
  yxorp:
    build: yxorp
    environment:
      - PROXY_URL=http://marketing:8000
    ports:
      - 8080:80

networks:
  default:
    external:
      name: itprotv_bridge
