version: '3'
services:
  marketing:
    build: .
    command: [ "gatsby", "develop", "--verbose", "-H", "0.0.0.0" ]
    ports:
      - 8000:8000
    volumes:
      - .:/work

networks:
  default:
    external:
      name: itprotv_bridge
