#!/bin/bash

if [ ! -f settings.env ]; then
  echo "No settings.env file exists. You need to configure these settings for terraform to work"
  echo ""
  echo "Run: cp settings.env.template settings.env"
  echo ""
  echo "And then edit the file to put in your creds"
  exit 1
fi

docker-compose run --rm terraform $@
