export { default as HomeHero } from './Home';
export { default as CoursesHero } from './Courses';
export { default as CourseCategoryHero } from './CourseCategory';
export { default as ForTeamsHero } from './ForTeams';
export { default as ForYouHero } from './ForYou';
export { default as OnAir } from './OnAir';
export { default as Plans } from './Plans';
export { default as Accessibility } from './Accessibility';
export { default as ThankYou } from './ThankYou';
