# Site settings
languageCode = "en-us"
baseurl = "https://itpro.tv/"
theme = "itprotv-2018"

[params]

  title = "Information Technology Training Courses Online - Video Computer Classes"
  brand = "ITProTV"
  description = "Easy to understand IT Training & Certification courses online. Grow your IT skills. Engaging videos with expert trainers. Start FREE now!"
  canonifyURLs = false

  googletagmanager = "GTM-KGKCZ2G" # Google tag manager for the staging container

  tagcategory = "tagcategory"
  tag = "tag"
  course = "course"

[sitemap]

  changefreq = "monthly"
  priority = 0.5
